#!/bin/bash

echo "Monitoring src for changes..."

inotifywait -q -m -r -e modify src | while read DIRECTORY EVENT FILE; do
  # echo $DIRECTORY $EVENT $FILE
  case $EVENT in
    MODIFY*)
      clear
      echo "= Cargo run ==============================="; echo
      cargo build && cargo run -q
      echo; echo "= $(date) ==================="
      ;;
  esac
done
