#!/bin/bash

EXE=${1:-"main"}
SRC="${EXE}.rs"

echo "Monitoring ${SRC} for changes..."

while ! inotifywait -e close_write,modify "${SRC}"; do
  rustc ${SRC}
  clear
  echo "= Build done; Running ==============================="; echo
  ./${EXE}
  echo; echo "= $(date) ==================="
done
